### PR TITLE
fix(notifications): Fix inconsistent action notification categories

### LINKED ISSUE #284: Notification Categories are inconsistent between actions
As a side note, while testing this I notice that "Recording Created" appears twice - once as a success and once as an info with more details. "Recording Archived" appears once, as an info. It's probably a good thing that this notification grouping makes this kind of detail about the notifications more obvious/visible. I'll file a separate issue for that.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-web/issues/283#issuecomment-919535403_

### PR DESCRIPTION
**Pull request by jan-law**
Fixes #284 

Only one notification should appear when recordings are created. All notifications indicating that a user's action was successfully processed now display the green "success" message style.

>  the subscription to this notification category should be somewhere long-lived

The NotificationChannel now subscribes to all WebSocket messages related to updating recording state (ie recording created/archived/saved/deleted) so that these notifications are displayed even if users navigate away from the Recordings page.

### CODE REVIEW

File: src/app/Notifications/Notifications.tsx [hunk 1]
```diff
@@ -145,7 +146,8 @@ export class Notifications {
   }
 
   private isNetworkInfoNotification(n: Notification): boolean {
-    return (n.category === 'WsClientActivity' || n.category === 'TargetJvmDiscovery')
+    return (n.category === NotificationCategory.WsClientActivity
+      || n.category === NotificationCategory.JvmDiscovery)
```
Comment (andrewazores) [inline src/app/Notifications/Notifications.tsx:150]: I think this function should at least be renamed, since JvmDiscovery doesn't seem like a "network info" or very related to WsClientActivity - but it would probably be better to split this into two functions.

**Comment by andrewazores** [comment]
Rather than "backend" status, could we say "Cryostat Status"?

**Review by andrewazores — APPROVED** [review]
