### PR TITLE
fix(label-upload): add error handler for metadata uploads

### LINKED ISSUE #623: [Task] Metadata file upload should handle parsing error
If the metadata file has invalid contents, the UI should handle this: either by showing an error text or just return empty. Right now, the UI will be stuck in loading state.

Screenshot from 2022-11-09 16-46-44

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #623 

Handled parsing error if user uploads invalid metadata label files. The invalid files are shown in a popover on top of the button since inline texts are taking quite some spaces and misaligned. In the background, invalid file contents are ignored (i.e. return empty []).

Screenshot from 2022-11-09 18-11-06

### CODE REVIEW

**Comment by tthvo** [comment]
Any thoughts on this design?

**Comment by andrewazores** [comment]
Design looks good. I think the two texts are mostly saying the same thing though, so either one should be rephrased or the one inside the component body should be removed.

Maybe,
title: "Invalid Selection"
message: "The following files did not contain valid recording metadata:"

**Review by andrewazores — COMMENTED** [review]
Code looks good

**Comment by tthvo** [comment]
> I think the two texts are mostly saying the same thing though, so either one should be rephrased or the one inside the component body should be removed.

Nice! Thanks I updated the modal now.

Screenshot from 2022-11-09 18-41-23

**Comment by andrewazores** [comment]
LGTM, I'll give @maxcao13 a chance to look at this too

File: src/app/RecordingMetadata/RecordingLabelFields.tsx [hunk 1]
```diff
@@ -187,9 +194,31 @@ export const RecordingLabelFields: React.FunctionComponent<RecordingLabelFieldsP
...
+            isVisible={!!invalidUploads.length}
+            aria-label="uploading warning"
+            alertSeverityVariant="danger"
+            headerContent="Invalid Selection"
+            headerComponent="h1"
+            shouldClose={closeWarningPopover}
+            headerIcon={<ExclamationCircleIcon />}
+            bodyContent={
+              <>
+                <Text component="h4">The following files did not contain valid recording metadata:</Text>
```
Comment (maxcao13) [inline src/app/RecordingMetadata/RecordingLabelFields.tsx:207]: The only thing I would consider is that making files -> `file(s)` because there might be only 1 file. But otherwise looks good!

Comment (tthvo) [reply src/app/RecordingMetadata/RecordingLabelFields.tsx]: Got it! Updated now :D

Comment (andrewazores) [reply src/app/RecordingMetadata/RecordingLabelFields.tsx]: May as well dynamically set the text to singular or plural depending on list size then ;-)

Comment (andrewazores) [reply src/app/RecordingMetadata/RecordingLabelFields.tsx]: Nice, I see Thuan just did that haha.

Gonna be fun when we get around to localizing these strings!

Comment (tthvo) [reply src/app/RecordingMetadata/RecordingLabelFields.tsx]: Hoping its not gonna be a nightmare XD

Comment (andrewazores) [reply src/app/RecordingMetadata/RecordingLabelFields.tsx]: #625
