### PR TITLE
fix(archive): all-archive should properly display when refreshing

### LINKED ISSUE #549: [Task] Refreshing causes incorrect display of All-Archives view
> There is a bug, probably not caused by this PR (and probably front-end related haven't checked main yet)but basically if you go to the archives view and have a target with archived recordings, wait for a autoRefresh, and the target and its archived recordings disappear. 

_Originally posted by @maxcao13 in https://github.com/cryostatio/cryostat/pull/1105#pullrequestreview-1137726916_

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #549 

**Fixes**

All Archive view now correctly refresh view when auto-refresh is enabled. The issue was that there is a call to `Array.includes`, which only checks object reference.

**Chore**

Counts of archives for each target should not be an saved in an array (i.e. sorting might be supported). Alternative was `Map<string, number>` with key is `target.connectUrl`. This way, subscriptions to notification channel are only called once in `React.useEffect` for each type.

### CODE REVIEW

File: src/app/Archives/Archives.tsx [hunk 1]
```diff
@@ -58,14 +59,16 @@ export const uploadAsTarget: Target = {
...
   const context = React.useContext(ServiceContext);
+  const addSubscription = useSubscriptions();
   const [activeTab, setActiveTab] = React.useState(0);
   const [archiveEnabled, setArchiveEnabled] = React.useState(false);
 
   React.useEffect(() => {
-    const sub = context.api.isArchiveEnabled().subscribe(setArchiveEnabled);
-    return () => sub.unsubscribe();
+    addSubscription(context.api.isArchiveEnabled().subscribe(setArchiveEnabled));
   }, [context.api]);
```
Comment (maxcao13) [inline src/app/Archives/Archives.tsx:72]: Do we need addSubscription in deps?

Comment (maxcao13) [reply src/app/Archives/Archives.tsx:72]: and setArchiveEnabled?

File: src/app/Archives/AllTargetsArchivedRecordingsTable.tsx [hunk 2]
```diff
@@ -170,18 +167,14 @@ export const AllTargetsArchivedRecordingsTable: React.FunctionComponent<AllTarge
...
-          return old.filter((o) => !_.isEqual(o, target));
+          return old.filter((t) => !isEqualTarget(t, target));
         });
-        setExpandedTargets((old) => old.filter((o) => !_.isEqual(o, target)));
+        setExpandedTargets((old) => old.filter((t) => !isEqualTarget(t, target)));
         setCounts((old) => {
-          let updated = [...old];
-          updated.splice(idx, 1);
-          return updated;
+          const newMap = new Map<string, number>(old);
```
Comment (maxcao13) [inline src/app/Archives/AllTargetsArchivedRecordingsTable.tsx:175]: I'm wondering if the map should be a `React.useState()` state instead of being generated every render. Is there something that prevents that from working?

Comment (maxcao13) [reply src/app/Archives/AllTargetsArchivedRecordingsTable.tsx:175]: Oh, I see the state is a map, but you are creating a new one and using the old one as an argument.

File: src/app/Archives/Archives.tsx (hunk 1 above)
Comment (tthvo) [reply src/app/Archives/Archives.tsx:72]: Yeh definitely! Sorry I missed that!

File: src/app/Archives/AllTargetsArchivedRecordingsTable.tsx (hunk 2 above)
Comment (tthvo) [reply src/app/Archives/AllTargetsArchivedRecordingsTable.tsx:175]: yeh I have to create new map since we have deps on hooks, which check if this map changes (i.e. obj ref).

**Review by maxcao13 — APPROVED** [review]
LGTM, bug is fixed.

**Review by andrewazores — APPROVED** [review]
