### PR TITLE
fix(rules): show error view and modal when template retrieving fails

### LINKED ISSUE #485: Different HTTP error types [4xx vs. 5xx] may be handled differently by the browser or by rxjs error handling
Not sure why, but `Observables<EventTemplate[]>` that are subscribed from `refreshTemplateList` that run into `Error 427: Client Error (JMX Authentication)` never complete until a a different valid target is queried, then both are completed (can see from console). But Observables that run into `Error 502: Bad Gateway (Target SSL Untrusted)`are caught by the `catchError` that is implemented and hence get completed correctly.

_Originally posted by @maxcao13 in https://github.com/cryostatio/cryostat-web/pull/483#issuecomment-1190676076_

### LINKED ISSUE #527: [Task] JMX Auth Modal prompt does not appear on Automated Rules creation form
When viewing the Automated Rules creation form we query the backend for the event templates available for the selected target JVM (if any is selected). This opens a JMX connection and therefore may require JMX credentials to be passed or stored so that Cryostat can check the TARGET templates. A similar data flow occurs on the Recordings and Events views, and a modal dialog appears prompting the user to enter JMX credentials. On the Automated Rule creation view the connection and HTTP request simply fail if credentials are required and an error notification appears. The standard JMX credentials auth modal should appear instead and, just like for Recordings/Events, the request should automatically re-fire if credentials are saved so that the event template selector can populate.

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #527 
Fixes #485 
Depends on https://github.com/cryostatio/cryostat/issues/1104

**Fixes**
- Added Auth form or SSL warning if failing to retrieve a template list from selected target.
- Editted ErrorView for better layout and visuals :D

**Chore**
- Use `useSubscriptions` for subs and `React.useCallback` for callbacks in `AppLayout`.

### CODE REVIEW

File: src/app/Rules/CreateRule.tsx [hunk 1]
```diff
@@ -243,6 +211,14 @@ const Comp = () => {
     maxSizeUnits,
   ]);
 
+  const handleTemlateList = React.useCallback(
```
Comment (andrewazores) [inline src/app/Rules/CreateRule.tsx:214]: typo: "Temlate"

Comment (tthvo) [reply src/app/Rules/CreateRule.tsx:214]: oh sorry haha :D

**Review by andrewazores — APPROVED** [review]

**Comment by tthvo** [comment]
Oh sorry I just added a new issue. I will fix it in a new PR :P
