### PR TITLE
fix(recordings): fix column alignments by converting data list components to table components

### LINKED ISSUE #130: Recording table headings and columns are misaligned
Here's a recent screenshot from @Alexjsenn  illustrating the problem:
image

The table headings of Name, Start Time, Duration, and State are not correctly aligned with the values in their columns (testing, timestamp, 30s, RUNNING). These should be correctly aligned in a vertical line so that ex. "testing" is directly below "Name", with both left-justified within the visual column whitespace.

### PR DESCRIPTION
**Pull request by aptmac**
This PR addresses https://github.com/cryostatio/cryostat-web/issues/130 [0], in which the table headings and columns are misaligned on the recordings tables.

Taking a look at the PatternFly design guidelines [[1]](https://www.patternfly.org/2020.11/design-guidelines/usage-and-behavior/lists-and-tables), they mention that if column headers are intended to be used then a table is likely the component of interest. Currently the component used is a data list, which is great for flexible layouts, but could be difficult to align properly.

My approach here is to merge a handful of the PatternFly table examples together to recreate the current recordings table using table components. A nice side-effect of using the table is how it is handled on a smaller screen size; each row turns into a nicely contained card, and I've attached a screenshot to show what it looks like.

In the example code for the expandable table [[2]](https://www.patternfly.org/v4/components/table/#composable-expandable), they created a row that contains a parent and child component. So now `RecordingRow` returns this:
```
<Tbody key={props.index} isExpanded={isExpanded[props.index]}>
  {parentRow}
  {childRow}
</Tbody>
``` 
where `parentRow` has the recording information, and `childRow` has the automated analysis content.

The empty table looked kind of funny, so I tossed in a basic empty state component for if there aren't any recordings. I've attached a screen shot of it below, let me know if that's okay or if any adjustments need to be made there.

Additionally I tried to fixup the ids, keys, and aria information to minimize the amount of warnings in the Chrome developer console. Let me know if any of them look out of place.

Lastly, I updated the file names to reflect the change from a list to a table. To help de-clutter the ActiveRecordingsList I put the code related to the row actions into it's own file. The directory was also called RecordingsList, which I guess is still applicable but I renamed it to simply "Recordings" to match the navigation tab in the ui. Let me know if any of these stand out like a sore thumb should be reverted.
```
RecordingsList.tsx -> Recordings.tsx
RecodingsDataTable.tsx -> RecordingsTable.tsx
ActiveRecordingsList.tsx -> ActiveRecordingsTable.tsx
ArchivedRecordingsList.tsx -> ArchivedRecordingsTable.tsx
ActiveRecordingsList.tsx RecordingActions -> RecordingActions.tsx
```

[0] https://github.com/cryostatio/cryostat-web/issues/130
[1] https://www.patternfly.org/2020.11/design-guidelines/usage-and-behavior/lists-and-tables
[2] https://www.patternfly.org/v4/components/table/#composable-expandable

Screenshots:

1). Active Recordings Table
1-active-recordings-table

2). Active Recordings Table with dropdown expanded
2-active-recordings-analysis

3). Archived Recordings Table
3-archived-recordings-table

4). Smaller screen size -> cards
4-cards

5). Archived Recordings empty state
5-empty-state

Fixes #130

### CODE REVIEW

File: src/app/Recordings/ActiveRecordingsTable.tsx [hunk 1]
```diff
@@ -98,8 +99,9 @@ export const ActiveRecordingsList: React.FunctionComponent<ActiveRecordingsListP
   const handleRecordings = React.useCallback((recordings) => {
     setRecordings(recordings);
     setIsLoading(false);
+    recordings.length === 0 ? setIsEmpty(true) : setIsEmpty(false);
```
Comment (andrewazores) [inline src/app/Recordings/ActiveRecordingsTable.tsx:102]: Just a style thing so feel free to take it or leave it, but this could be written as `setIsEmpty(recordings.length === 0)` or even `setIsEmpty(!recordings.length)`

Comment (andrewazores) [reply src/app/Recordings/ActiveRecordingsTable.tsx:102]: Or just a standard if/else, rather than this ternary where the expression value isn't actually used

File: src/app/Recordings/ArchivedRecordingsTable.tsx [hunk 2]
```diff
@@ -84,7 +86,8 @@ export const ArchivedRecordingsList: React.FunctionComponent<ArchivedRecordingsL
   const handleRecordings = React.useCallback((recordings) => {
     setRecordings(recordings);
     setIsLoading(false);
-  }, [setRecordings, setIsLoading]);
+    recordings.length === 0 ? setIsEmpty(true) : setIsEmpty(false);
```
Comment (andrewazores) [inline src/app/Recordings/ArchivedRecordingsTable.tsx:89]: Same here

File: src/app/Recordings/ActiveRecordingsTable.tsx [hunk 3]
```diff
@@ -227,50 +229,78 @@ export const ActiveRecordingsList: React.FunctionComponent<ActiveRecordingsListP
...
+            {props.recording.state}
+          </Td>
+          <RecordingActions
+            index={props.index}
+            recording={props.recording}
+            uploadFn={() => context.api.uploadActiveRecordingToGrafana(props.recording.name)}
+          />
+        </Tr>
+      )
+    }, [props.recording, props.recording.name, props.duration, props.index]);
```
Comment (andrewazores) [inline src/app/Recordings/ActiveRecordingsTable.tsx:271]: I think the memo dependencies array here should also contain `handleCheck`, `checkedIndices`, `props.index`, `isExpanded`, `handleToggle`, `tableColumns`, `props.recording.startTime`, `props.recording.duration`, `props.recording.state`, and `context.api`

File: src/app/Recordings/ActiveRecordingsTable.tsx [hunk 4]
```diff
@@ -227,50 +229,78 @@ export const ActiveRecordingsList: React.FunctionComponent<ActiveRecordingsListP
...
+              <br></br>
+              <hr></hr>
+              <br></br>
+              <Text>Automated Analysis:</Text>
+              <ReportFrame isExpanded={isExpanded} recording={props.recording} width="100%" height="640" />
+            </ExpandableRowContent>
+          </Td>
+        </Tr>
+      );
     }, [props.recording, props.recording.name, props.duration, props.index]);
```
Comment (andrewazores) [inline src/app/Recordings/ActiveRecordingsTable.tsx:297]: This deps array is also missing some members

File: src/app/Recordings/ArchivedRecordingsTable.tsx [hunk 5]
```diff
@@ -148,29 +151,61 @@ export const ArchivedRecordingsList: React.FunctionComponent<ArchivedRecordingsL
...
-          id={`archived-ex-expand-${props.index}`}
-          isHidden={!isExpanded}
-        >
-          <ReportFrame isExpanded={isExpanded} recording={props.recording} width="100%" height="640" />
-        </DataListContent>
-      </DataListItem>
-    </>);
+        </Tr>
+      );
+    }, [props.recording, props.recording.name, props.index]);
```
Comment (andrewazores) [inline src/app/Recordings/ArchivedRecordingsTable.tsx:185]: This deps array is also missing some members

File: src/app/Recordings/ArchivedRecordingsTable.tsx [hunk 6]
```diff
@@ -148,29 +151,61 @@ export const ArchivedRecordingsList: React.FunctionComponent<ArchivedRecordingsL
...
+            dataLabel={"Content Details"}
+            colSpan={tableColumns.length + 3}
+          >
+          <ExpandableRowContent>
+            <ReportFrame isExpanded={isExpanded} recording={props.recording} width="100%" height="640" />
+          </ExpandableRowContent>
+          </Td>
+        </Tr>
+      )
+    }, [props.recording, props.recording.name, props.index]);
```
Comment (andrewazores) [inline src/app/Recordings/ArchivedRecordingsTable.tsx:201]: This deps array is also missing some members

File: src/app/Recordings/RecordingActions.tsx [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+      props.uploadFn()
+      .pipe(first())
+      .subscribe(success => {
+        if (success) {
+          notifications.success('Upload Success', `Recording "${props.recording.name}" uploaded`);
+          context.api.grafanaDashboardUrl().pipe(first()).subscribe(url => window.open(url, '_blank'));
+        }
+      })
+    );
+  }, [addSubscription]);
```
Comment (andrewazores) [inline src/app/Recordings/RecordingActions.tsx:79]: This needs `notifications`, `props.uploadFn`, and `context.api`

**Review by andrewazores — COMMENTED** [review]
Code changes overall look good and the improved UI is really great - thanks for this!

File: src/app/Recordings/ActiveRecordingsTable.tsx (hunk 3 above)
Comment (aptmac) [reply src/app/Recordings/ActiveRecordingsTable.tsx:271]: Sounds good, I'll add these in.

For the case of `props.recording.whatever`, do they need to be separate entries into the dependencies array? Or would `props.recording` suffice?

Comment (andrewazores) [reply src/app/Recordings/ActiveRecordingsTable.tsx:271]: I think in practice, `props.recording` would be enough - however this could be broken if the `recording` prop passed to the child component is updated in-place by mutating its state without changing the reference of the `recording` object. It's probably safest to specifically list out each of the properties of the `recording` object. Otherwise, if the parent component mutates the recording object without replacing it, these effects in the child component won't re-run/memos won't recalculate/etc.

Comment (aptmac) [reply src/app/Recordings/ActiveRecordingsTable.tsx:271]: Ah right, sounds good

**Review by andrewazores — APPROVED** [review]
