### PR TITLE
fix(snapshots): remove successful snapshot creation notification handling

### LINKED ISSUE #426: Snapshot creation notification handling should be delegated to the backend
Frontend equivalent of [#916](https://github.com/cryostatio/cryostat/issues/916).

### PR DESCRIPTION
**Pull request by hareetd**
Fixes #426

### CODE REVIEW

**Comment by andrewazores** [comment]
Once the backend does emit a notification when a snapshot is created then the frontend will need a [notification category and mapper ](https://github.com/cryostatio/cryostat-web/blob/5a9b7be1febcb0698a2a31144c64b159cbfe302a/src/app/Shared/Services/NotificationChannel.service.tsx#L80) added. Would you like to do that within this PR or create a second one for that separately?

**Comment by hareetd** [comment]
I think doing it in this one would make sense, I'll create notification categories for "Snapshot Created" and "Snapshot Deleted".

File: src/app/Recordings/ActiveRecordingsTable.tsx [hunk 1]
```diff
@@ -129,7 +129,10 @@ export const ActiveRecordingsTable: React.FunctionComponent<ActiveRecordingsTabl
     addSubscription(
       combineLatest([
         context.target.target(),
-        context.notificationChannel.messages(NotificationCategory.ActiveRecordingCreated),
+        merge(
```
Comment (andrewazores) [inline src/app/Recordings/ActiveRecordingsTable.tsx:132]: What does the `merge` here do?

Comment (hareetd) [reply src/app/Recordings/ActiveRecordingsTable.tsx:132]: Without the `merge` the web client doesn't properly update the table state upon receiving `ActiveRecordingDeleted` or `SnapshotDeleted` notifications. I included it here as well for consistency reasons even though the `ActiveRecordingCreated` and `SnapshotCreated` notifications don't exhibit the same behavior, although that's likely because a refresh is triggered upon returning from the `/create` route and not because the table is properly updating its state based on the notifications alone.

I think the reason why `combineLatest` doesn't work on its own is that it won't emit an initial value until each of the Observables comprising it doesn't emit at least once. For example, that means the first time an `ActiveRecordingDeleted` notification is received, `combineLatest` won't emit until it also receives a `SnapshotDeleted` notification, which leads to weird state behavior in the displayed table. 

However, by merging snapshot and active recording notification Observables into one, it ensures that `combineLatest` will emit soon as either a snapshot or active recording-related notification is received.

Comment (andrewazores) [reply src/app/Recordings/ActiveRecordingsTable.tsx:132]: Ahh, that makes sense. Thanks.

**Review by andrewazores — APPROVED** [review]
